In [1]:
import numpy as np

In [2]:
"""
通过列表创建
注意：
1. NumPy 要求数组必须包含同一类型的数据。如果类型不匹配，NumPy 将会向上转换。
"""
a = np.array([1,4,2,5,3])
print(a)
b = np.array([3.14,4,2,3])
print(b)

[1 4 2 5 3]
[3.14 4.   2.   3.  ]


In [4]:
"""
明确设置数组的数据类型，可以用 dtype 关键字
"""
np.array([1,2,3,4],dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [5]:
"""
创建多维数组
"""
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## NumPy 内置相关函数创建数组

In [6]:
# 创建一个长度为 10 的数据，数组的值都是 0
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# 创建一个 3 * 5 的浮点型数组，数组的值都是 1
np.ones((3,5),dtype="float32")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [8]:
# 创建一个 3 * 5 的浮点型数组，数组的值都是 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
# 从 0 开始，到 20 结束，步长为 2，它和内置的 range() 函数类似
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# 创建一个 5 个元素的数组，这 5 个数均匀地分配到 0~1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# 创建一个 3 * 3 的、在 0~1 均匀分布的随机数组成的数组
np.random.random((3,3))

array([[0.76680249, 0.61729914, 0.96942101],
       [0.48654426, 0.52861012, 0.46447843],
       [0.41829821, 0.40628836, 0.52878727]])

In [12]:
# 创建一个 3 * 3 的、均值为 0、方差为 1 的正态分布的随机数数组
np.random.normal(0,1,(3,3))

array([[ 1.09331059,  1.91709619, -0.24784801],
       [ 1.11657806,  0.50811977,  0.39497817],
       [ 0.06354374,  0.6442754 , -0.15340177]])

In [13]:
# 创建一个 3 * 3 的、[0, 10)区间的随机整型数组
np.random.randint(0,10,(3,3))

array([[3, 3, 7],
       [4, 2, 3],
       [6, 5, 1]])

In [14]:
# 创建一个 3 * 3 的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## NumPy 数组的基础

In [15]:
"""
NumPy 数组的属性
    每个数组都有 ndim（数组的维度）、shape（数组每个维度的大小）和 size（数组的总大小）属性
"""
# 设置 NumPy 的随机数生成器的一组种子值，以确保每次程序执行时都可以生成同样的随机数组
np.random.seed(0)

x1=np.random.randint(10,size=6)       # 一维数组 
x2=np.random.randint(10,size=(3,4))   # 二维数组
x3=np.random.randint(10,size=(3,4,5)) # 三维数组

print("x3 ndim:",x3.ndim)
print("x3 shape:",x3.shape)
print("x3 size:",x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [16]:
"""
获取单个元素
"""
# 一维数组操作
print(x1)
print(x1[0])
print(x1[4])
print(x1[-1])
print(x1[-2])

# 二维数组操作
print(x2)
print(x2[0,0])
print(x2[2,0])
print(x2[2,-1])

[5 0 3 3 7 9]
5
7
9
7
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
1
7


In [18]:
"""
数组切片：获取子数组
"""
x=np.arange(10)
print(x)
# 获取前五个元素
print(x[:5])
# 获取索引五之后的元素
print(x[5:])
# 中间的子数组
print(x[4:7])
# 每隔一个元素的数组
print(x[::2])
# 每隔一个元素的数组，从索引 1 开始
print(x[1::2])
# 所有元素，逆序的
print(x[::-1])
# 从索引五开始每隔一个元素逆序
print(x[5::-2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [21]:
"""
数组运算
"""
x = np.arange(4)
print("x     =",x)
print("x + 5 =",x+5)
print("x - 5 =",x-5)
print("x * 2 =",x*2)
print("x / 2 =",x/2)
print("x // 2 =",x//2)

"""
还支持逻辑非，指数运算和模运算
"""
print("-x    =",-x)
print("x ** 2 =",x**2)
print("x % 2 =",x%2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x    = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]
