# NumPy

NumPy 提供了种种基本的对象：

- ndarray(N-dimensional array object)
    存储单一数据类型的多维数组
- ufunc(universal function object)
    能够对数组进行处理的函数

In [2]:
"""
函数库导入
    推荐使用如下方式进行导入
"""
import numpy as np

In [2]:
"""
创建数组

1. 直接通过传入列表来进行创建，如果传递的是多层嵌套的列表将会创建多维数组
2. 通过 numpy 自带的函数来创建函数
"""
# 通过传入列表直接进行创建
a=np.array([1,2,3,4])
print(a)
b=np.array([[1,2,3,4],[5,6,7,8],[7,8,9,10]])
print(b)
# arange 函数类似于 python 的 range 函数，通过指定开始值、终值和步长来创建一维数组
## 注意：数组不包含终值
c=np.arange(1,10,1)
print(c)
# linspace 函数通过指定开始值、终值和元素个数来创建一维数组，可以通过 endpoint 关键字指定是否包括终值，缺省设置时包括终值的：
d=np.linspace(0,10,100)
# logspace 函数和 linspace 类似，不过它创建等比数列
f=np.logspace(0,2,20)
# random 函数生成随机 4*4 数组
g=np.random.rand(4,4)
# 使用 frombuffer,fromstring,fromfile 等函数可以从字节序列创建数组

[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  9 10]]
[1 2 3 4 5 6 7 8 9]


In [3]:
"""
数组的属性
"""
# 获取数组的大小
print(a.shape) # 该结果只有一个元素，因此它是一维数组
print(b.shape)
# 数组的元素类型
print(a.dtype)

(4,)
(3, 4)
int32


In [4]:
"""
改变数组的形状

1. 可以通过修改数组的 shape 属性，在保持元素个数不变的情况下，改变数组每个轴的长度
2. 使用数组的 reshape 函数，可以创建一个改变了尺寸的新数组，原数组的 shape 保持不变
"""
# 方法一：
# 将 b 数组的 shape 从 (3,4) 变为 (4,3)
b.shape=4,3
print(b)
# 当某个轴的元素为 -1 时，将根据数组元素的个数自动计算此轴的长度，因此下例将数组 b 的 shape 改为了 (2,6)
b.shape=2,-1
print(b)
# 方法二：
# reshape 不会改变原数组的结构
a2=a.reshape((2,2))
print(a2)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  7]
 [ 8  9 10]]
[[ 1  2  3  4  5  6]
 [ 7  8  7  8  9 10]]
[[1 2]
 [3 4]]
[1 2 3 4]


In [5]:
"""
存取元素
"""
# 用整数下标可以获取数组中的某个元素
print(c[5])
# 使用范围作为下标获取数组的一个切片，包括起点，但不包括结束点
print(c[3:5])
# 省略开始下标，表示从 0 开始
print(c[:5])
# 下标可以使用负数，表示从数组后往前数
print(c[:-1])
# 下标还可以用来修改元素的值
c[2:4]=100,101
print(c)
# 范围中的第三个参数表示步长，例如，步长为 2 表示隔一个元素取一个元素
print(c[1:-1:2])
# 省略范围的开始下标和结束下标，步长为 -1，整个数组倒排
print(c[::-1])
# 步长为负数时，开始下标必须大于结束下标
print(c[5:1:-2])

6
[4 5]
[1 2 3 4 5]
[1 2 3 4 5 6 7 8]
[  1   2 100 101   5   6   7   8   9]
[  2 101   6   8]
[  9   8   7   6   5 101 100   2   1]
[  6 101]


In [7]:
"""
除了使用下标范围存取元素之外，NumPy 还提供了两种存取元素的高级方法

1. 使用整数序列
    当使用整数序列对数组元素进行存取时，将使用整数序列中的每个元素作为下标，整数序列可以是列表或者数组。
    注意：使用整数序列作为下标获得的数组不和原始数组共享数据空间
2. 使用布尔数组
    当使用布尔数组作为下标存取数组中的元素时，将收集数组中所有在布尔数组中对应下标为 True 的元素
    使用布尔数组作为下标获得的数组不和原始数组共享数据空间
    注意：只能使用布尔数组而不能使用布尔列表
"""
# 使用整数序列
## 获取 c 中的下标为 3，3，1，8 的 4 个元素，组成一个新的数组
print(c[[3,3,1,8]])
## 下标也可以是负数
print(c[np.array([3,3,-3,8])])
# 使用布尔数组
## 布尔数组中下标为 0，2 的元素为 True，因此获取数组中下标为 0，2 的元素
print(a[np.array([True,False,True,False])])
## 如果使用布尔列表，则把 True 当作 1，False 当为 0，按照整数序列方式获取数组中的元素
print(a[[True,False,True,False]])
## 布尔数组一般不是手动产生的，而是通过布尔运算的 ufunc 函数产生的
print(a%2==0)
print(a[a%2==0])

[101 101   2   9]
[101 101   7   9]
[1 3]
[1 3]
[False  True False  True]
[2 4]


In [3]:
"""
矩阵
"""
# 将数组转换成矩阵
arr=np.arange(0,1,0.1)
mat=np.mat(arr)
print(mat)
# 对矩阵求逆
mat_i=mat.I
print(mat_i)
#矩阵和自身逆矩阵得到单位矩阵
##注意：存在一些非对角线的元素是由于计算机处理误差造成的
my_eye=mat*mat_i
print(my_eye)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]]
[[0.        ]
 [0.03508772]
 [0.07017544]
 [0.10526316]
 [0.14035088]
 [0.1754386 ]
 [0.21052632]
 [0.24561404]
 [0.28070175]
 [0.31578947]]
[[1.]]
