In [1]:
import numpy as np

In [ ]:
r_arr=np.random.rand(4,4)

In [ ]:
#将数组转换成矩阵
r_mat=np.mat(r_arr)
r_mat

In [ ]:
#对矩阵求逆
r_mat_i=r_mat.I
r_mat_i

In [ ]:
#矩阵和自身逆矩阵得到单位矩阵
##注意：存在一些非对角线的元素是由于计算机处理误差造成的
my_eye=r_mat*r_mat_i
my_eye

In [4]:
# 一维
x=np.array([1,2,3,4,5])
print(x)
print(x.shape)

# 二维
y=np.array([[1,2,3],[4,5,6]])
print(y)
print(y.shape)

# 三维
z=np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(z)
print(z.shape)


[1 2 3 4 5]
(5,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
(3, 2, 1)
